version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel_app
        restart: always
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "9000:9000"
        networks:
            - laravel-network

    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: always
        ports:
            - "8080:80"
        depends_on:
            - app
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel-network

networks:
    laravel-network: